### PR TITLE
Remove some stuff that is not relevant to Ecostage

### PR DESCRIPTION
**Pull request by mateusmedeiros**
Some things, specially the rails part of the protocol guide, will look like it has relevant info at a first glance. In reality, though, the guide is tailored for Thoughbot's continuous deployment. It won't fit our workflow and I think the most useful part of it would be the part where a project is created with the suspenders gem. 

The problem is that I also don't think the gem as it is is very suitable for us, so I removed the section and [forked the gem](https://github.com/ecostage/suspenders.git).

When we adjust the suspenders gem to fit our needs, we can then add a new protocol guide for rails with a simple guide to kickstart a project.

### CODE REVIEW

**Comment by mpivaa** [comment]
I think we could leave other languages(who knows the future, there are mobile things around), and about rails protocol guide, I've started `web-collect` following thoughtbot's workflow and its `almost` fitting. Instead of exclude we should leave as it is and tweak both suspenders and the guide with our workflow.

**Comment by mateusmedeiros** [comment]
@mpivaa Can't we just get back those things if we need them in the future? They will always be there in the history of the repository. I think we should get the thoughtbot guide and tweak it to the ecostage reality, instead of getting the thoughtbot guide and tweaking ecostage reality to it.

**Comment by mateusmedeiros** [comment]
@ecostage/developers No one else has anything to say?

**Comment by diegotoral** [comment]
We should keep our guides as clean as possible and remove everything that don't matter to us. Let's focus on what is important right now and add more later.

**Comment by karydja** [comment]
I think @diegotoral and @mateusmedeiros are right. This amount of information (which we don't need right now) sometimes confuses more than helps. If we start using some new technology, in the future, we can just add its guides here, since we have the repo history.

**Comment by mpivaa** [comment]
I agree, but lets build our rails protocol guide. I think its a priority. I will open a PR sometime this week to discuss our base workflow with all teams. Tweak suspenders would be great too, specially with our new assets pipeline.

**Comment by mpivaa** [comment]
:shipit:

**Comment by karydja** [comment]
:shipit: 
@mpivaa: You're right when you say Rails protocol is our priority (such as the Ruby one).Thoughbot guides are a great way to start, but now it's time to adapt them to our needs, and what I think is that our needs, at the moment, are simpler then theirs, as we can notice taking a look at the HUGE [suspender's Gemfile](https://github.com/ecostage/suspenders#gemfile)

**Comment by mateusmedeiros** [comment]
@mpivaa By all means. As I mentioned in the first message, I'm not removing the rails protocol guide because I don't think it is important, just because I think the current one isn't exactly what we need.

A simple edit should also do, I just chose to remove it because it is the quickest path for now, as we're all right now busy as hell :sweat_smile:.
Tweaking the suspenders gem is a great start, yes. I'll be sure to take a good look at it when I have the time, it's just something too big to make a priority RIGHT now.

@ecostage/developers Anyone want to say anything else? Can I merge it?

**Comment by mpivaa** [comment]
:+1: The priority is our projets, this would take time that we don't have.

**Comment by jaimerson** [comment]
:shipit:

**Pull request merged**
